baseURL = "//jelenko.crnjak.xyz/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

disqusShortname = "jelenko-b"

DefaultContentLanguage = "en"
copyright = "Everything is mine"

[languages]
  [languages.en]
    title = "Moving images in space-time"
    homepageTitle = "Home"
    weight = 1
  [languages.hr]
    languageCode = "hr-HR"
    title = "Pokretne slike u prostor-vremenu"
    homepageTitle = "Početna"
    weight = 2
    [languages.hr.params]
      [languages.hr.params.navigation]
        help = "Pomoć"

[params]
  mainURL = "//jelenko.crnjak.xyz"
  [params.navigation]
    help = "Help"
